// Ülkeler listesi (ISO 3166-1 alpha-2 kodları ile)
export const countries = [
    { code: 'AF', name: 'Afganistan' },
    { code: 'AL', name: 'Arnavutluk' },
    { code: 'DZ', name: 'Cezayir' },
    { code: 'AS', name: 'Amerikan Samoası' },
    { code: 'AD', name: 'Andorra' },
    { code: 'AO', name: 'Angola' },
    { code: 'AI', name: 'Anguilla' },
    { code: 'AQ', name: 'Antarktika' },
    { code: 'AG', name: 'Antigua ve Barbuda' },
    { code: 'AR', name: 'Arjantin' },
    { code: 'AM', name: 'Ermenistan' },
    { code: 'AW', name: 'Aruba' },
    { code: 'AU', name: 'Avustralya' },
    { code: 'AT', name: 'Avusturya' },
    { code: 'AZ', name: 'Azerbaycan' },
    { code: 'BS', name: 'Bahamalar' },
    { code: 'BH', name: 'Bahreyn' },
    { code: 'BD', name: 'Bangladeş' },
    { code: 'BB', name: 'Barbados' },
    { code: 'BY', name: 'Belarus' },
    { code: 'BE', name: 'Belçika' },
    { code: 'BZ', name: 'Belize' },
    { code: 'BJ', name: 'Benin' },
    { code: 'BM', name: 'Bermuda' },
    { code: 'BT', name: 'Bhutan' },
    { code: 'BO', name: 'Bolivya' },
    { code: 'BA', name: 'Bosna-Hersek' },
    { code: 'BW', name: 'Botsvana' },
    { code: 'BR', name: 'Brezilya' },
    { code: 'BN', name: 'Brunei' },
    { code: 'BG', name: 'Bulgaristan' },
    { code: 'BF', name: 'Burkina Faso' },
    { code: 'BI', name: 'Burundi' },
    { code: 'KH', name: 'Kamboçya' },
    { code: 'CM', name: 'Kamerun' },
    { code: 'CA', name: 'Kanada' },
    { code: 'CV', name: 'Cabo Verde' },
    { code: 'KY', name: 'Cayman Adaları' },
    { code: 'CF', name: 'Orta Afrika Cumhuriyeti' },
    { code: 'TD', name: 'Çad' },
    { code: 'CL', name: 'Şili' },
    { code: 'CN', name: 'Çin' },
    { code: 'CO', name: 'Kolombiya' },
    { code: 'KM', name: 'Komorlar' },
    { code: 'CG', name: 'Kongo' },
    { code: 'CD', name: 'Kongo Demokratik Cumhuriyeti' },
    { code: 'CR', name: 'Kosta Rika' },
    { code: 'CI', name: 'Fildişi Sahili' },
    { code: 'HR', name: 'Hırvatistan' },
    { code: 'CU', name: 'Küba' },
    { code: 'CY', name: 'Kıbrıs' },
    { code: 'CZ', name: 'Çekya' },
    { code: 'DK', name: 'Danimarka' },
    { code: 'DJ', name: 'Cibuti' },
    { code: 'DM', name: 'Dominika' },
    { code: 'DO', name: 'Dominik Cumhuriyeti' },
    { code: 'EC', name: 'Ekvador' },
    { code: 'EG', name: 'Mısır' },
    { code: 'SV', name: 'El Salvador' },
    { code: 'GQ', name: 'Ekvator Ginesi' },
    { code: 'ER', name: 'Eritre' },
    { code: 'EE', name: 'Estonya' },
    { code: 'ET', name: 'Etiyopya' },
    { code: 'FJ', name: 'Fiji' },
    { code: 'FI', name: 'Finlandiya' },
    { code: 'FR', name: 'Fransa' },
    { code: 'GA', name: 'Gabon' },
    { code: 'GM', name: 'Gambiya' },
    { code: 'GE', name: 'Gürcistan' },
    { code: 'DE', name: 'Almanya' },
    { code: 'GH', name: 'Gana' },
    { code: 'GR', name: 'Yunanistan' },
    { code: 'GD', name: 'Grenada' },
    { code: 'GT', name: 'Guatemala' },
    { code: 'GN', name: 'Gine' },
    { code: 'GW', name: 'Gine-Bissau' },
    { code: 'GY', name: 'Guyana' },
    { code: 'HT', name: 'Haiti' },
    { code: 'HN', name: 'Honduras' },
    { code: 'HK', name: 'Hong Kong' },
    { code: 'HU', name: 'Macaristan' },
    { code: 'IS', name: 'İzlanda' },
    { code: 'IN', name: 'Hindistan' },
    { code: 'ID', name: 'Endonezya' },
    { code: 'IR', name: 'İran' },
    { code: 'IQ', name: 'Irak' },
    { code: 'IE', name: 'İrlanda' },
    { code: 'IL', name: 'İsrail' },
    { code: 'IT', name: 'İtalya' },
    { code: 'JM', name: 'Jamaika' },
    { code: 'JP', name: 'Japonya' },
    { code: 'JO', name: 'Ürdün' },
    { code: 'KZ', name: 'Kazakistan' },
    { code: 'KE', name: 'Kenya' },
    { code: 'KI', name: 'Kiribati' },
    { code: 'KP', name: 'Kuzey Kore' },
    { code: 'KR', name: 'Güney Kore' },
    { code: 'KW', name: 'Kuveyt' },
    { code: 'KG', name: 'Kırgızistan' },
    { code: 'LA', name: 'Laos' },
    { code: 'LV', name: 'Letonya' },
    { code: 'LB', name: 'Lübnan' },
    { code: 'LS', name: 'Lesotho' },
    { code: 'LR', name: 'Liberya' },
    { code: 'LY', name: 'Libya' },
    { code: 'LI', name: 'Liechtenstein' },
    { code: 'LT', name: 'Litvanya' },
    { code: 'LU', name: 'Lüksemburg' },
    { code: 'MO', name: 'Makao' },
    { code: 'MK', name: 'Kuzey Makedonya' },
    { code: 'MG', name: 'Madagaskar' },
    { code: 'MW', name: 'Malavi' },
    { code: 'MY', name: 'Malezya' },
    { code: 'MV', name: 'Maldivler' },
    { code: 'ML', name: 'Mali' },
    { code: 'MT', name: 'Malta' },
    { code: 'MH', name: 'Marshall Adaları' },
    { code: 'MR', name: 'Moritanya' },
    { code: 'MU', name: 'Mauritius' },
    { code: 'MX', name: 'Meksika' },
    { code: 'FM', name: 'Mikronezya' },
    { code: 'MD', name: 'Moldova' },
    { code: 'MC', name: 'Monako' },
    { code: 'MN', name: 'Moğolistan' },
    { code: 'ME', name: 'Karadağ' },
    { code: 'MA', name: 'Fas' },
    { code: 'MZ', name: 'Mozambik' },
    { code: 'MM', name: 'Myanmar' },
    { code: 'NA', name: 'Namibya' },
    { code: 'NR', name: 'Nauru' },
    { code: 'NP', name: 'Nepal' },
    { code: 'NL', name: 'Hollanda' },
    { code: 'NZ', name: 'Yeni Zelanda' },
    { code: 'NI', name: 'Nikaragua' },
    { code: 'NE', name: 'Nijer' },
    { code: 'NG', name: 'Nijerya' },
    { code: 'NO', name: 'Norveç' },
    { code: 'OM', name: 'Umman' },
    { code: 'PK', name: 'Pakistan' },
    { code: 'PW', name: 'Palau' },
    { code: 'PS', name: 'Filistin' },
    { code: 'PA', name: 'Panama' },
    { code: 'PG', name: 'Papua Yeni Gine' },
    { code: 'PY', name: 'Paraguay' },
    { code: 'PE', name: 'Peru' },
    { code: 'PH', name: 'Filipinler' },
    { code: 'PL', name: 'Polonya' },
    { code: 'PT', name: 'Portekiz' },
    { code: 'PR', name: 'Porto Riko' },
    { code: 'QA', name: 'Katar' },
    { code: 'RO', name: 'Romanya' },
    { code: 'RU', name: 'Rusya' },
    { code: 'RW', name: 'Ruanda' },
    { code: 'KN', name: 'Saint Kitts ve Nevis' },
    { code: 'LC', name: 'Saint Lucia' },
    { code: 'VC', name: 'Saint Vincent ve Grenadinler' },
    { code: 'WS', name: 'Samoa' },
    { code: 'SM', name: 'San Marino' },
    { code: 'ST', name: 'São Tomé ve Príncipe' },
    { code: 'SA', name: 'Suudi Arabistan' },
    { code: 'SN', name: 'Senegal' },
    { code: 'RS', name: 'Sırbistan' },
    { code: 'SC', name: 'Seyşeller' },
    { code: 'SL', name: 'Sierra Leone' },
    { code: 'SG', name: 'Singapur' },
    { code: 'SK', name: 'Slovakya' },
    { code: 'SI', name: 'Slovenya' },
    { code: 'SB', name: 'Solomon Adaları' },
    { code: 'SO', name: 'Somali' },
    { code: 'ZA', name: 'Güney Afrika' },
    { code: 'SS', name: 'Güney Sudan' },
    { code: 'ES', name: 'İspanya' },
    { code: 'LK', name: 'Sri Lanka' },
    { code: 'SD', name: 'Sudan' },
    { code: 'SR', name: 'Surinam' },
    { code: 'SZ', name: 'Eswatini' },
    { code: 'SE', name: 'İsveç' },
    { code: 'CH', name: 'İsviçre' },
    { code: 'SY', name: 'Suriye' },
    { code: 'TW', name: 'Tayvan' },
    { code: 'TJ', name: 'Tacikistan' },
    { code: 'TZ', name: 'Tanzanya' },
    { code: 'TH', name: 'Tayland' },
    { code: 'TL', name: 'Doğu Timor' },
    { code: 'TG', name: 'Togo' },
    { code: 'TO', name: 'Tonga' },
    { code: 'TT', name: 'Trinidad ve Tobago' },
    { code: 'TN', name: 'Tunus' },
    { code: 'TR', name: 'Türkiye' },
    { code: 'TM', name: 'Türkmenistan' },
    { code: 'TV', name: 'Tuvalu' },
    { code: 'UG', name: 'Uganda' },
    { code: 'UA', name: 'Ukrayna' },
    { code: 'AE', name: 'Birleşik Arap Emirlikleri' },
    { code: 'GB', name: 'Birleşik Krallık' },
    { code: 'US', name: 'Amerika Birleşik Devletleri' },
    { code: 'UY', name: 'Uruguay' },
    { code: 'UZ', name: 'Özbekistan' },
    { code: 'VU', name: 'Vanuatu' },
    { code: 'VA', name: 'Vatikan' },
    { code: 'VE', name: 'Venezuela' },
    { code: 'VN', name: 'Vietnam' },
    { code: 'YE', name: 'Yemen' },
    { code: 'ZM', name: 'Zambiya' },
    { code: 'ZW', name: 'Zimbabve' }
] as const;

// Diller listesi (ISO 639-1 kodları ile)
export const languages = [
    { code: 'aa', name: 'Afar' },
    { code: 'ab', name: 'Abhazca' },
    { code: 'ae', name: 'Avestan' },
    { code: 'af', name: 'Afrikaanca' },
    { code: 'ak', name: 'Akan' },
    { code: 'am', name: 'Amharca' },
    { code: 'an', name: 'Aragonca' },
    { code: 'ar', name: 'Arapça' },
    { code: 'as', name: 'Assamca' },
    { code: 'av', name: 'Avarca' },
    { code: 'ay', name: 'Aymara' },
    { code: 'az', name: 'Azerice' },
    { code: 'ba', name: 'Başkurtça' },
    { code: 'be', name: 'Belarusça' },
    { code: 'bg', name: 'Bulgarca' },
    { code: 'bh', name: 'Bihari' },
    { code: 'bi', name: 'Bislama' },
    { code: 'bm', name: 'Bambara' },
    { code: 'bn', name: 'Bengalce' },
    { code: 'bo', name: 'Tibetçe' },
    { code: 'br', name: 'Bretonca' },
    { code: 'bs', name: 'Boşnakça' },
    { code: 'ca', name: 'Katalanca' },
    { code: 'ce', name: 'Çeçence' },
    { code: 'ch', name: 'Chamorro' },
    { code: 'co', name: 'Korsikaca' },
    { code: 'cr', name: 'Cree' },
    { code: 'cs', name: 'Çekçe' },
    { code: 'cu', name: 'Eski Kilise Slavcası' },
    { code: 'cv', name: 'Çuvaşça' },
    { code: 'cy', name: 'Galce' },
    { code: 'da', name: 'Danca' },
    { code: 'de', name: 'Almanca' },
    { code: 'dv', name: 'Divehi' },
    { code: 'dz', name: 'Dzongkha' },
    { code: 'ee', name: 'Ewe' },
    { code: 'el', name: 'Yunanca' },
    { code: 'en', name: 'İngilizce' },
    { code: 'eo', name: 'Esperanto' },
    { code: 'es', name: 'İspanyolca' },
    { code: 'et', name: 'Estonca' },
    { code: 'eu', name: 'Baskça' },
    { code: 'fa', name: 'Farsça' },
    { code: 'ff', name: 'Fulah' },
    { code: 'fi', name: 'Fince' },
    { code: 'fj', name: 'Fijice' },
    { code: 'fo', name: 'Faroe Dili' },
    { code: 'fr', name: 'Fransızca' },
    { code: 'fy', name: 'Batı Frizcesi' },
    { code: 'ga', name: 'İrlandaca' },
    { code: 'gd', name: 'İskoç Galcesi' },
    { code: 'gl', name: 'Galiçyaca' },
    { code: 'gn', name: 'Guarani' },
    { code: 'gu', name: 'Güceratça' },
    { code: 'gv', name: 'Manks' },
    { code: 'ha', name: 'Hausa' },
    { code: 'he', name: 'İbranice' },
    { code: 'hi', name: 'Hintçe' },
    { code: 'ho', name: 'Hiri Motu' },
    { code: 'hr', name: 'Hırvatça' },
    { code: 'ht', name: 'Haiti Creole' },
    { code: 'hu', name: 'Macarca' },
    { code: 'hy', name: 'Ermenice' },
    { code: 'hz', name: 'Herero' },
    { code: 'ia', name: 'Interlingua' },
    { code: 'id', name: 'Endonezce' },
    { code: 'ie', name: 'Interlingue' },
    { code: 'ig', name: 'İgbo' },
    { code: 'ii', name: 'Sichuan Yi' },
    { code: 'ik', name: 'İnupiaq' },
    { code: 'io', name: 'Ido' },
    { code: 'is', name: 'İzlandaca' },
    { code: 'it', name: 'İtalyanca' },
    { code: 'iu', name: 'İnuktitut' },
    { code: 'ja', name: 'Japonca' },
    { code: 'jv', name: 'Cavaca' },
    { code: 'ka', name: 'Gürcüce' },
    { code: 'kg', name: 'Kongo' },
    { code: 'ki', name: 'Kikuyu' },
    { code: 'kj', name: 'Kuanyama' },
    { code: 'kk', name: 'Kazakça' },
    { code: 'kl', name: 'Grönlandca' },
    { code: 'km', name: 'Khmer' },
    { code: 'kn', name: 'Kannada' },
    { code: 'ko', name: 'Korece' },
    { code: 'kr', name: 'Kanuri' },
    { code: 'ks', name: 'Keşmir Dili' },
    { code: 'ku', name: 'Kürtçe' },
    { code: 'kv', name: 'Komi' },
    { code: 'kw', name: 'Kernevekçe' },
    { code: 'ky', name: 'Kırgızca' },
    { code: 'la', name: 'Latince' },
    { code: 'lb', name: 'Lüksemburgca' },
    { code: 'lg', name: 'Ganda' },
    { code: 'li', name: 'Limburgca' },
    { code: 'ln', name: 'Lingala' },
    { code: 'lo', name: 'Laoca' },
    { code: 'lt', name: 'Litvanca' },
    { code: 'lu', name: 'Luba-Katanga' },
    { code: 'lv', name: 'Letonca' },
    { code: 'mg', name: 'Malgaşça' },
    { code: 'mh', name: 'Marshallca' },
    { code: 'mi', name: 'Maori' },
    { code: 'mk', name: 'Makedonca' },
    { code: 'ml', name: 'Malayalam' },
    { code: 'mn', name: 'Moğolca' },
    { code: 'mr', name: 'Marathi' },
    { code: 'ms', name: 'Malayca' },
    { code: 'mt', name: 'Maltaca' },
    { code: 'my', name: 'Birmanca' },
    { code: 'na', name: 'Nauru' },
    { code: 'nb', name: 'Norveççe Bokmål' },
    { code: 'nd', name: 'Kuzey Ndebele' },
    { code: 'ne', name: 'Nepalce' },
    { code: 'ng', name: 'Ndonga' },
    { code: 'nl', name: 'Felemenkçe' },
    { code: 'nn', name: 'Norveççe Nynorsk' },
    { code: 'no', name: 'Norveççe' },
    { code: 'nr', name: 'Güney Ndebele' },
    { code: 'nv', name: 'Navaho' },
    { code: 'ny', name: 'Chichewa' },
    { code: 'oc', name: 'Oksitanca' },
    { code: 'oj', name: 'Ojibwe' },
    { code: 'om', name: 'Oromo' },
    { code: 'or', name: 'Oriya' },
    { code: 'os', name: 'Osetçe' },
    { code: 'pa', name: 'Pencapça' },
    { code: 'pi', name: 'Pali' },
    { code: 'pl', name: 'Lehçe' },
    { code: 'ps', name: 'Peştuca' },
    { code: 'pt', name: 'Portekizce' },
    { code: 'qu', name: 'Keçuva' },
    { code: 'rm', name: 'Romanşça' },
    { code: 'rn', name: 'Kirundi' },
    { code: 'ro', name: 'Rumence' },
    { code: 'ru', name: 'Rusça' },
    { code: 'rw', name: 'Kinyarwanda' },
    { code: 'sa', name: 'Sanskritçe' },
    { code: 'sc', name: 'Sardunya Dili' },
    { code: 'sd', name: 'Sindhi' },
    { code: 'se', name: 'Kuzey Sami' },
    { code: 'sg', name: 'Sango' },
    { code: 'si', name: 'Sinhala' },
    { code: 'sk', name: 'Slovakça' },
    { code: 'sl', name: 'Slovence' },
    { code: 'sm', name: 'Samoaca' },
    { code: 'sn', name: 'Shona' },
    { code: 'so', name: 'Somalice' },
    { code: 'sq', name: 'Arnavutça' },
    { code: 'sr', name: 'Sırpça' },
    { code: 'ss', name: 'Swati' },
    { code: 'st', name: 'Güney Sotho' },
    { code: 'su', name: 'Sundaca' },
    { code: 'sv', name: 'İsveççe' },
    { code: 'sw', name: 'Svahili' },
    { code: 'ta', name: 'Tamilce' },
    { code: 'te', name: 'Telugu' },
    { code: 'tg', name: 'Tacikçe' },
    { code: 'th', name: 'Tayca' },
    { code: 'ti', name: 'Tigrinya' },
    { code: 'tk', name: 'Türkmence' },
    { code: 'tl', name: 'Tagalogca' },
    { code: 'tn', name: 'Tswana' },
    { code: 'to', name: 'Tonga' },
    { code: 'tr', name: 'Türkçe' },
    { code: 'ts', name: 'Tsonga' },
    { code: 'tt', name: 'Tatarca' },
    { code: 'tw', name: 'Twi' },
    { code: 'ty', name: 'Tahitice' },
    { code: 'ug', name: 'Uygurca' },
    { code: 'uk', name: 'Ukraynaca' },
    { code: 'ur', name: 'Urduca' },
    { code: 'uz', name: 'Özbekçe' },
    { code: 've', name: 'Venda' },
    { code: 'vi', name: 'Vietnamca' },
    { code: 'vo', name: 'Volapük' },
    { code: 'wa', name: 'Valonca' },
    { code: 'wo', name: 'Wolof' },
    { code: 'xh', name: 'Xhosa' },
    { code: 'yi', name: 'Yidiş' },
    { code: 'yo', name: 'Yoruba' },
    { code: 'za', name: 'Zhuang' },
    { code: 'zh', name: 'Çince' },
    { code: 'zu', name: 'Zuluca' }
] as const;

// Type tanımlamaları
export type Country = typeof countries[number];
export type Language = typeof languages[number];
export type CountryCode = Country['code'];
export type LanguageCode = Language['code'];